### ISSUE TITLE
Restructure how backend returns PRO data

### ISSUE THREAD

**Issue by bbobateaa** [ojosproject/iris#50]
### Summary

Group the responses, date from the data together by question
for example:
in python it would be

{ questions : [[response, date], [response, date]]}

### Concept images and/or code

![Uploading Screen Shot 2024-11-21 at 1.55.14 PM.png…]()

**Comment by calejvaldez** [comment]
Fixed in 547ac51e7987d78bd6b14f85850e08d0fccdefe5
