### ISSUE TITLE
gi library isn't being properly imported into scope

### ISSUE THREAD

**Issue by AyushJain2021** [ojosproject/iris#9]
### Summary

The line that's importing gi library in `main.py` just doesn't seem to recognize it. @calejvaldez mentions that it could be a dependency issue.

### What is the expected correct behavior?

gi should be imported properly, and we should be able to important `gi.repository.Glib` and `gi.repository.GtK` 

### Steps to reproduce

Open `main.py` as seen from `dev` branch

### Relevant logs and/or screenshots

![image](https://github.com/ojosproject/iris/assets/97090874/ae917f5c-6c2d-4f42-8039-c635f9cf98b3)

### Operating System

Windows

### Browser

Firefox

**Comment by calejvaldez** [comment]
No longer required since we won't be using Python anymore.
